### ISSUE TITLE
请问测试精度和torch版相差的比较多 漏检变多了

### ISSUE THREAD

**Issue by seyosum** [JiaoPaner/detector-tensorrt-yolov5-linux#2]
有可能是什么原因导致的呢？

**Comment by JiaoPaner** [comment]
@seyosum 你用的那个模型

**Comment by seyosum** [comment]
@JiaoPaner 用的yolov5s，单类别的时候检测结果和转换前的精度差别不是很大，多类别时检测精度就会掉很多

**Comment by JiaoPaner** [comment]
@seyosum 是自己的数据训练的模型吗 调调参数试试

**Comment by JiaoPaner** [comment]
@seyosum yolo_layer.h的CLASS_NUM也要修改一下

**Comment by seyosum** [comment]
@JiaoPaner 是我用自己的数据进行训练的，数据的类别和大小都修改过了，nms和min_score都修改了，计算结果误差很大，我目前还没找到是哪里的问题，但是我在单类目标的检测上面测试了，结果和之前差别是很小的，但是换到多类目标的时候检测结果差距就变大了，我目前还没找到原因，找到后我会告知您的，也是用的U版的3.1版本

**Comment by JiaoPaner** [comment]
@seyosum emmm... repo的yolov5版本是3.0的  你换个3.0训练的模型试试

**Comment by seyosum** [comment]
@JiaoPaner 好的 我试试 多谢回复呀
